// Generated by CoffeeScript 1.7.1
(function() {
  define(['text!cdeio/layouts/templates/tree.html'], function() {
    return {
      regions: {
        toolbar: 'toolbar',
        body: 'body'
      }
    };
  });

}).call(this);
