// Generated by CoffeeScript 1.7.1
(function() {
  define({
    regions: {
      operators: "operators",
      grid: "grid",
      completedOperators: "completedOperators",
      completedGrid: "completedGrid"
    },
    avoidLoadingHandlers: true
  });

}).call(this);
