// Generated by CoffeeScript 1.7.1
(function() {
  define({
    extend: {
      templateHelpers: function() {
        var title;
        title = this.feature.startupOptions.title;
        return {
          title: title
        };
      }
    },
    avoidLoadingHandlers: true
  });

}).call(this);
