// Generated by CoffeeScript 1.7.1
(function() {
  define({
    layout: 'cdeio:one-region',
    views: [
      {
        name: 'grid-view',
        region: 'main'
      }
    ],
    avoidLoadingModel: true
  });

}).call(this);
